
version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres_db_container
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
